version: "3"

services:
  db:
    container_name: "database"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=party
      - MYSQL_USER=josuel
      - MYSQL_PASSWORD=Joj@1994
      - MYSQL_ROOT_PASSWORD=Joj@1994
  app:
    container_name: "NodeMIP"
    build: .
    command: npm start
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
